/**
 * Declarative description of every control in the panel.
 *
 * One entry per parameter in ENGINE_SPEC section 8, grouped into the seven
 * sections of UI_SPEC section 3. `explain` is the one-line, plain-English,
 * physical meaning shown under the control — it is the difference between a
 * lab instrument and a form.
 *
 * kind: 'slider' | 'toggle' | 'segmented' | 'weights' | 'seed' | 'aircraft' | 'strategy' | 'doors'
 */

export const SECTIONS = [
  { id: 'scenario', title: 'Scenario', hint: 'What is being boarded, and how' },
  { id: 'doors', title: 'Doors', hint: 'Where passengers get on' },
  { id: 'passengers', title: 'Passengers', hint: 'Who is on the flight' },
  { id: 'timing', title: 'Timing', hint: 'How long each action takes' },
  { id: 'bins', title: 'Overhead bins', hint: 'Where the bags go' },
  { id: 'behaviour', title: 'Behaviour', hint: 'How well the plan survives contact with people' },
  { id: 'presets', title: 'Presets & sharing', hint: 'Whole scenarios in one click' },
]

const pct = (v) => `${(v * 100).toFixed(v * 100 < 10 ? 1 : 0)}%`
const secs = (v) => `${v.toFixed(1)}s`
const mps = (v) => `${v.toFixed(2)} m/s`
const plain = (v) => `${v}`
const fixed2 = (v) => v.toFixed(2)

/** @type {Array<object>} */
export const CONTROLS = [
  // ---------------------------------------------------------------- scenario
  {
    key: 'aircraftId',
    kind: 'aircraft',
    section: 'scenario',
    label: 'Aircraft',
    explain: 'The airframe: its seat map, pitch, aisle count and door positions.',
  },
  {
    key: 'strategy',
    kind: 'strategy',
    section: 'scenario',
    label: 'Boarding strategy',
    explain: 'The rule the gate uses to decide who walks down the jet bridge next.',
  },
  {
    key: 'loadFactor',
    kind: 'slider',
    section: 'scenario',
    label: 'Load factor',
    min: 0.3,
    max: 1,
    step: 0.01,
    format: pct,
    explain: 'How full the aircraft is — the fraction of seats with a body in them.',
  },
  {
    key: 'seed',
    kind: 'seed',
    section: 'scenario',
    label: 'Random seed',
    explain: 'Fixes every random draw, so the same seed replays the exact same flight.',
  },
  {
    key: 'runs',
    kind: 'slider',
    section: 'scenario',
    label: 'Replications',
    min: 10,
    max: 1000,
    step: 10,
    format: plain,
    explain: 'How many independent flights to simulate per strategy in Analytics and Compare.',
  },

  // ------------------------------------------------------------------- doors
  {
    key: 'doors',
    kind: 'doors',
    section: 'doors',
    label: 'Active doors',
    explain: 'Which doors are actually open. Each open door runs its own queue, in parallel.',
  },
  {
    key: 'doorAssignment',
    kind: 'segmented',
    section: 'doors',
    label: 'Door assignment',
    options: [
      { value: 'single', label: 'Single' },
      { value: 'split_by_row', label: 'By row' },
      { value: 'split_by_aisle', label: 'By aisle' },
    ],
    explain: 'How a passenger is told which door to use: one door for all, nearest door by row, or the door feeding their aisle.',
  },

  // -------------------------------------------------------------- passengers
  {
    key: 'bagWeights',
    kind: 'weights',
    section: 'passengers',
    label: 'Carry-on mix',
    keys: ['0', '1', '2'],
    keyLabels: { 0: 'No bag', 1: '1 bag', 2: '2 bags' },
    explain: 'How many overhead bags people bring. Bags are the single biggest driver of aisle time.',
  },
  {
    key: 'partySizeWeights',
    kind: 'weights',
    section: 'passengers',
    label: 'Party-size mix',
    keys: ['1', '2', '3', '4', '5'],
    keyLabels: { 1: 'Solo', 2: 'Pair', 3: 'Three', 4: 'Four', 5: 'Five' },
    explain: 'How many people travel together. Groups sit together and insist on boarding together.',
  },
  {
    key: 'walkSpeedMean',
    kind: 'slider',
    section: 'passengers',
    label: 'Walk speed (mean)',
    min: 0.4,
    max: 1.6,
    step: 0.01,
    format: mps,
    explain: 'Free-flow walking pace down an empty aisle. About 0.9 m/s is a normal unhurried walk.',
  },
  {
    key: 'walkSpeedSd',
    kind: 'slider',
    section: 'passengers',
    label: 'Walk speed spread',
    min: 0,
    max: 0.5,
    step: 0.01,
    format: fixed2,
    explain: 'Spread of walking pace across people. Bigger means more dawdlers behind whom everyone piles up.',
  },
  {
    key: 'preboardRate',
    kind: 'slider',
    section: 'passengers',
    label: 'Preboards',
    min: 0,
    max: 0.2,
    step: 0.005,
    format: pct,
    explain: 'Share needing wheelchair or assistance boarding, or unaccompanied minors — they board before everyone.',
  },
  {
    key: 'slowPaxRate',
    kind: 'slider',
    section: 'passengers',
    label: 'Reduced mobility',
    min: 0,
    max: 0.4,
    step: 0.005,
    format: pct,
    explain: 'Share who walk and stow noticeably slower without needing formal assistance.',
  },
  {
    key: 'slowSpeedFactor',
    kind: 'slider',
    section: 'passengers',
    label: 'Reduced-mobility pace',
    min: 0.2,
    max: 1,
    step: 0.01,
    format: fixed2,
    explain: 'How much slower those passengers walk, as a multiple of normal pace.',
  },
  {
    key: 'slowStowFactor',
    kind: 'slider',
    section: 'passengers',
    label: 'Reduced-mobility stow',
    min: 1,
    max: 3,
    step: 0.05,
    format: fixed2,
    explain: 'How much longer those passengers take to lift a bag into the bin.',
  },
  {
    key: 'childRate',
    kind: 'slider',
    section: 'passengers',
    label: 'Travelling with children',
    min: 0,
    max: 0.6,
    step: 0.01,
    format: pct,
    explain: 'Share of multi-person parties that include a child — they board as a unit and settle slowly.',
  },
  {
    key: 'eliteMix',
    kind: 'weights',
    section: 'passengers',
    label: 'Status mix',
    keys: ['elite_top', 'elite_mid', 'cardholder', 'standard', 'basic'],
    keyLabels: {
      elite_top: 'Top elite',
      elite_mid: 'Mid elite',
      cardholder: 'Cardholder',
      standard: 'Standard',
      basic: 'Basic',
    },
    explain: 'Frequent-flyer tiers in the main cabin. Revenue-driven strategies board these in order.',
  },

  // ------------------------------------------------------------------ timing
  {
    key: 'stowBaseMean',
    kind: 'slider',
    section: 'timing',
    label: 'Stow time (1 bag)',
    min: 3,
    max: 30,
    step: 0.5,
    format: secs,
    explain: 'How long a typical passenger takes to heave one bag into the overhead bin.',
  },
  {
    key: 'stowCv',
    kind: 'slider',
    section: 'timing',
    label: 'Stow variability',
    min: 0,
    max: 1.2,
    step: 0.01,
    format: fixed2,
    explain: 'Run-to-run randomness in a single stow, as a fraction of its mean.',
  },
  {
    key: 'stowBagExponent',
    kind: 'slider',
    section: 'timing',
    label: 'Second-bag exponent',
    min: 0.5,
    max: 1.3,
    step: 0.01,
    format: fixed2,
    explain: 'How much cheaper the second bag is than the first. Below 1.0, two bags take less than twice as long.',
  },
  {
    key: 'stowVariability',
    kind: 'slider',
    section: 'timing',
    label: 'Per-person dexterity spread',
    min: 0,
    max: 0.8,
    step: 0.01,
    format: fixed2,
    explain: 'How much people differ from each other in handling luggage — some are simply quicker every time.',
  },
  {
    key: 'shuffleTime.1',
    kind: 'slider',
    section: 'timing',
    label: 'Shuffle past 1 person',
    min: 2,
    max: 25,
    step: 0.5,
    format: secs,
    explain: 'Time lost when one already-seated neighbour has to get up to let you in.',
  },
  {
    key: 'shuffleTime.2',
    kind: 'slider',
    section: 'timing',
    label: 'Shuffle past 2 people',
    min: 4,
    max: 40,
    step: 0.5,
    format: secs,
    explain: 'Time lost when two seated neighbours have to get up — the window-seat-arrives-last penalty.',
  },
  {
    key: 'shuffleCv',
    kind: 'slider',
    section: 'timing',
    label: 'Shuffle variability',
    min: 0,
    max: 1.2,
    step: 0.01,
    format: fixed2,
    explain: 'Randomness in how long a seat shuffle takes.',
  },
  {
    key: 'shuffleSamePartyTime',
    kind: 'slider',
    section: 'timing',
    label: 'Shuffle within a party',
    min: 0,
    max: 12,
    step: 0.5,
    format: secs,
    explain: 'Much faster: your own family stands up for you without the polite negotiation.',
  },
  {
    key: 'gateScanMean',
    kind: 'slider',
    section: 'timing',
    label: 'Gate scan interval',
    min: 0.5,
    max: 10,
    step: 0.1,
    format: secs,
    explain: 'Seconds between boarding-pass scans — the rate the gate can physically feed the jet bridge.',
  },
  {
    key: 'gateScanSd',
    kind: 'slider',
    section: 'timing',
    label: 'Gate scan spread',
    min: 0,
    max: 5,
    step: 0.1,
    format: secs,
    explain: 'Variability of the scan interval: misread passes, seat changes, arguments.',
  },

  // -------------------------------------------------------------------- bins
  {
    key: 'binBagsPerRowSide',
    kind: 'slider',
    section: 'bins',
    label: 'Bin capacity per row-side',
    min: 1,
    max: 10,
    step: 1,
    format: plain,
    explain: 'How many bags fit in the bin above one side of one row. Low-cost cabins fit fewer.',
  },
  {
    key: 'binSearchRadius',
    kind: 'slider',
    section: 'bins',
    label: 'Bin search radius',
    min: 0,
    max: 8,
    step: 1,
    format: (v) => `${v} rows`,
    explain: 'How many rows away a passenger will wander looking for a free bin before giving up.',
  },
  {
    key: 'binSearchPenalty',
    kind: 'slider',
    section: 'bins',
    label: 'Bin search penalty',
    min: 0,
    max: 15,
    step: 0.5,
    format: secs,
    explain: 'Extra seconds spent per row of displacement while hunting for space.',
  },
  {
    key: 'gateCheckPenalty',
    kind: 'slider',
    section: 'bins',
    label: 'Gate-check penalty',
    min: 0,
    max: 90,
    step: 1,
    format: secs,
    explain: 'The full stop when a bag has to go back down the jet bridge — tag, wait, hand over.',
  },
  {
    key: 'binCongestionWeight',
    kind: 'slider',
    section: 'bins',
    label: 'Full-bin fiddle factor',
    min: 0,
    max: 1.5,
    step: 0.05,
    format: fixed2,
    explain: 'How much longer stowing takes as a bin fills up and bags must be rearranged.',
  },

  // --------------------------------------------------------------- behaviour
  {
    key: 'zoneCount',
    kind: 'slider',
    section: 'behaviour',
    label: 'Zone count',
    min: 2,
    max: 8,
    step: 1,
    format: plain,
    explain: 'How many row bands the gate calls. More zones means finer control and more announcements.',
  },
  {
    key: 'keepPartiesTogether',
    kind: 'toggle',
    section: 'behaviour',
    label: 'Keep parties together',
    explain: 'Families board as a block at their earliest member’s turn — the main reason clever orderings fall apart.',
  },
  {
    key: 'preboardFirst',
    kind: 'toggle',
    section: 'behaviour',
    label: 'Preboards first',
    explain: 'Assistance passengers are lifted to the front of the queue before anything else is applied.',
  },
  {
    key: 'nonComplianceRate',
    kind: 'slider',
    section: 'behaviour',
    label: 'Non-compliance',
    min: 0,
    max: 0.5,
    step: 0.005,
    format: pct,
    explain: 'Share of passengers who ignore their group call and drift up or down the queue.',
  },
  {
    key: 'complianceJitter',
    kind: 'slider',
    section: 'behaviour',
    label: 'Non-compliance drift',
    min: 0,
    max: 25,
    step: 1,
    format: (v) => `±${v}`,
    explain: 'How far out of position those passengers end up, in queue places.',
  },
  {
    key: 'lateRate',
    kind: 'slider',
    section: 'behaviour',
    label: 'Late arrivals',
    min: 0,
    max: 0.12,
    step: 0.002,
    format: pct,
    explain: 'Share who turn up after their group has gone and board at the very end.',
  },
  {
    key: 'openSeatingPolicy',
    kind: 'segmented',
    section: 'behaviour',
    label: 'Open-seating choice',
    options: [
      { value: 'aisle_first', label: 'Aisle' },
      { value: 'window_first', label: 'Window' },
      { value: 'front_first', label: 'Nearest' },
      { value: 'avoid_neighbours', label: 'Spread out' },
    ],
    explain: 'With no assigned seats, what passengers reach for as they walk in.',
  },
  {
    key: 'dt',
    kind: 'slider',
    section: 'behaviour',
    label: 'Engine time step',
    min: 0.05,
    max: 0.5,
    step: 0.05,
    format: secs,
    advanced: true,
    explain: 'Simulation tick length. Smaller is more exact and slower; 0.1 s is the calibrated value.',
  },
  {
    key: 'sampleInterval',
    kind: 'slider',
    section: 'behaviour',
    label: 'Metric sample interval',
    min: 0.5,
    max: 10,
    step: 0.5,
    format: secs,
    advanced: true,
    explain: 'How often curves are recorded. Only affects chart resolution, never the result.',
  },
]

export const CONTROLS_BY_SECTION = SECTIONS.reduce((acc, s) => {
  acc[s.id] = CONTROLS.filter((c) => c.section === s.id)
  return acc
}, {})
